GitlabCIMultiRunner:
  image: sameersbn/gitlab-ci-multi-runner:0.7.2
  volumes:
    - /srv/docker/gitlab-runner:/home/gitlab-runner/data
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=
    - RUNNER_EXECUTOR=shell
  restart: always
